module.exports = [
  {
    uppercamelcase: 'Blit',
    lowercamelcase: 'blit',
    snakecase: 'BLIT',
    description: 'ブール関数を使用して複数の画像を1つに結合する',
  },
  { uppercamelcase: 'Blur', lowercamelcase: 'blur', snakecase: 'BLUR', description: 'ぼかし' },
  { uppercamelcase: 'Color', lowercamelcase: 'color', snakecase: 'COLOR', description: '色の調整' },
  {
    uppercamelcase: 'Contain',
    lowercamelcase: 'contain',
    snakecase: 'CONTAIN',
    description: 'アスペクト比を維持しつつ指定された幅と高さに収まるように拡大／縮小する',
  },
  {
    uppercamelcase: 'Cover',
    lowercamelcase: 'cover',
    snakecase: 'COVER',
    description: 'アスペクト比を維持しつつ指定された幅と高さを満たして表示されるよう拡大／縮小する',
  },
  { uppercamelcase: 'Displace', lowercamelcase: 'displace', snakecase: 'DISPLACE', description: '画像を歪ませる' },
  { uppercamelcase: 'Dither', lowercamelcase: 'dither', snakecase: 'DITHER', description: 'ノイズ' },
  { uppercamelcase: 'Flip', lowercamelcase: 'flip', snakecase: 'FLIP', description: '水平または垂直に反転する' },
  { uppercamelcase: 'Gaussian', lowercamelcase: 'gaussian', snakecase: 'GAUSSIAN', description: 'ガウスぼかし' },
  { uppercamelcase: 'Invert', lowercamelcase: 'invert', snakecase: 'INVERT', description: '色の反転' },
  { uppercamelcase: 'Mask', lowercamelcase: 'mask', snakecase: 'MASK', description: 'マスク' },
  { uppercamelcase: 'Normalize', lowercamelcase: 'normalize', snakecase: 'NORMALIZE', description: '色の正規化' },
  { uppercamelcase: 'Print', lowercamelcase: 'print', snakecase: 'PRINT', description: '文字の描画' },
  { uppercamelcase: 'Resize', lowercamelcase: 'resize', snakecase: 'RESIZE', description: 'リサイズ' },
  { uppercamelcase: 'Rotate', lowercamelcase: 'rotate', snakecase: 'ROTATE', description: '回転' },
  { uppercamelcase: 'Scale', lowercamelcase: 'scale', snakecase: 'SCALE', description: '拡大／縮小' },
];
