module.exports = [
  {
    lowercamelcase: 'adjoin',
    uppercamelcase: 'Adjoin',
    snakecase: 'ADJOIN',
    name: '画像の結合',
    description: '複数の画像を一つの画像に結合することができる。',
  },
  {
    lowercamelcase: 'affine',
    uppercamelcase: 'Affine',
    snakecase: 'AFFINE',
    argDefs: ['matrix: string;'],
    args: 'matrix',
    name: 'アフィン変換',
    description:
      '画像にアフィン変換を適用することができる。平行移動、回転、スケーリング、シアーなどの変換が可能である。',
  },
  {
    lowercamelcase: 'antialias',
    uppercamelcase: 'Antialias',
    snakecase: 'ANTIALIAS',
    argDefs: ['enable: boolean;'],
    args: 'enable',
    name: 'アンチエイリアス処理',
    description: '画像のアンチエイリアス処理を行うことができる。エッジや線を滑らかにすることができる。',
  },
  {
    lowercamelcase: 'append',
    uppercamelcase: 'Append',
    snakecase: 'APPEND',
    argDefs: ['image: string | string[];', 'ltr?: boolean;'],
    args: 'image,ltr',
    name: '画像の連結',
    description: '複数の画像を連結して一つの画像にすることができる。',
  },
  {
    lowercamelcase: 'authenticate',
    uppercamelcase: 'Authenticate',
    snakecase: 'AUTHENTICATE',
    argDefs: ['password: string;'],
    args: 'password',
    name: '認証',
    description: '画像の認証を行うことができる。特定の画像が正当であるかどうかを確認できる。',
  },
  {
    lowercamelcase: 'autoOrient',
    uppercamelcase: 'AutoOrient',
    snakecase: 'AUTO_ORIENT',
    name: '自動方向転換',
    description:
      '画像の向きを自動的に修正することができる。例えば、Exif情報に基づいて画像を正しい向きに回転させることができる。',
  },
  {
    lowercamelcase: 'average',
    uppercamelcase: 'Average',
    snakecase: 'AVERAGE',
    name: '平均値算出',
    description: '複数の画像の平均値を計算することができる。統計情報の取得や複数の画像をブレンドするのに使用できる。',
  },
  {
    lowercamelcase: 'backdrop',
    uppercamelcase: 'Backdrop',
    snakecase: 'BACKDROP',
    name: '背景画像',
    description: '画像の背景を指定した画像に設定することができる。',
  },
  {
    lowercamelcase: 'background',
    uppercamelcase: 'Background',
    snakecase: 'BACKGROUND',
    argDefs: ['color: string;'],
    args: 'color',
    name: '背景色',
    description: '背景を設定することができる。画像に背景色を追加する。',
  },
  {
    lowercamelcase: 'bitdepth',
    uppercamelcase: 'Bitdepth',
    snakecase: 'BITDEPTH',
    argDefs: ['bits: number;'],
    args: 'bits',
    name: 'ビット深度',
    description: '画像のビット深度を変更することができる。色の表現精度を調整することができる。',
  },
  {
    lowercamelcase: 'blackThreshold',
    uppercamelcase: 'BlackThreshold',
    snakecase: 'BLACK_THRESHOLD',
    argDefs: ['intensity: number;', 'red: number;', 'green: number;', 'blue: number;', 'opacity?: number;'],
    args: 'intensity,red,green,blue,opacity',
    name: '黒のしきい値',
    description: '画像の黒色の閾値を設定することができる。指定された閾値より暗いピクセルを黒色として扱うことができる。',
  },
  {
    lowercamelcase: 'bluePrimary',
    uppercamelcase: 'BluePrimary',
    snakecase: 'BLUE_PRIMARY',
    argDefs: ['x: number;', 'y: number;'],
    args: 'x,y',
    name: '青の主要成分',
    description: '画像の青のプライマリ値を設定することができる。',
  },
  {
    lowercamelcase: 'blur',
    uppercamelcase: 'Blur',
    snakecase: 'BLUR',
    argDefs: ['radius: number;', 'sigma?: number;'],
    args: 'radius,sigma',
    name: 'ぼかし',
    description: '画像にぼかしを適用することができる。これにより、画像のエッジが滑らかになり、ノイズが軽減される。',
  },
  {
    lowercamelcase: 'border',
    uppercamelcase: 'Border',
    snakecase: 'BORDER',
    argDefs: ['width: number;', 'height: number;'],
    args: 'width,height',
    name: '境界線',
    description: '画像に境界線を追加することができる。境界線は、画像の周囲にフレームを付けるのに使用される。',
  },
  {
    lowercamelcase: 'borderColor',
    uppercamelcase: 'BorderColor',
    snakecase: 'BORDER_COLOR',
    argDefs: ['color: string;'],
    args: 'color',
    name: '境界線色',
    description:
      '境界線の色を設定することができる。境界線の色は、画像に追加されるフレームの色を指定するのに使用される。',
  },
  {
    lowercamelcase: 'box',
    uppercamelcase: 'Box',
    snakecase: 'BOX',
    argDefs: ['color: string;'],
    args: 'color',
    name: 'ボックスフィルタ',
    description: '画像にボックスフィルタを適用することができる。ボックスフィルタは、画像をぼかすのに使用される。',
  },
  {
    lowercamelcase: 'channel',
    uppercamelcase: 'Channel',
    snakecase: 'CHANNEL',
    argDefs: ['channelType: NamedColor | string;'],
    args: 'channelType',
    name: 'チャンネル操作',
    description:
      '画像の特定のチャンネルを操作することができる。RGBやCMYKなどのチャンネルに対して、異なる処理を適用することができる。',
  },
  {
    lowercamelcase: 'charcoal',
    uppercamelcase: 'Charcoal',
    snakecase: 'CHARCOAL',
    argDefs: ['factor: number;'],
    args: 'factor',
    name: '木炭効果',
    description: '画像に木炭効果を適用することができる。木炭効果は、画像に粗い質感を与えるのに使用される。',
  },
  {
    lowercamelcase: 'chop',
    uppercamelcase: 'Chop',
    snakecase: 'CHOP',
    argDefs: ['width: number;', 'height: number;', 'x?: number;', 'y?: number;'],
    args: 'width,height,x,y',
    name: '切り取り',
    description: '画像から指定された範囲を切り取ることができる。指定された範囲外の部分が削除される。',
  },
  {
    lowercamelcase: 'clip',
    uppercamelcase: 'Clip',
    snakecase: 'CLIP',
    name: 'クリップ',
    description:
      '画像をクリッピングすることができる。指定された範囲内のピクセルのみが残り、それ以外のピクセルは削除される。',
  },
  {
    lowercamelcase: 'coalesce',
    uppercamelcase: 'Coalesce',
    snakecase: 'COALESCE',
    name: 'アニメーション',
    description: '複数の画像を連結することができる。複数の画像を連結して一つのアニメーション画像にする。',
  },
  {
    lowercamelcase: 'colorize',
    uppercamelcase: 'Colorize',
    snakecase: 'COLORIZE',
    argDefs: ['red: number;', 'green: number;', 'blue: number;'],
    args: 'red,green,blue',
    name: '着色',
    description: '画像に色を付けることができる。画像全体または指定された領域に色を塗ることができる。',
  },
  {
    lowercamelcase: 'colorMap',
    uppercamelcase: 'ColorMap',
    snakecase: 'COLOR_MAP',
    argDefs: ["colorMapType: 'shared' | 'private' | string;"],
    args: 'colorMapType',
    name: 'カラーマップ',
    description: '画像の色をマッピングすることができる。指定されたカラーマップに基づいて、画像の色を変換する。',
  },
  {
    lowercamelcase: 'colors',
    uppercamelcase: 'Colors',
    snakecase: 'COLORS',
    argDefs: ['colors: number;'],
    args: 'colors',
    name: '色数変更',
    description: '画像の色数を変更することができる。色数の変更により、画像の色の表現を調整することができる。',
  },
  {
    lowercamelcase: 'colorspace',
    uppercamelcase: 'Colorspace',
    snakecase: 'COLORSPACE',
    argDefs: ['space: ColorSpace | string;'],
    args: 'space',
    name: 'カラースペース変更',
    description:
      '画像のカラースペースを変更することができる。RGB、CMYK、グレースケールなどのカラースペースに変換することができる。',
  },
  // {
  //   lowercamelcase: 'command',
  //   uppercamelcase: 'Command',
  //   snakecase: 'COMMAND',
  //   argDefs: ['customCommand: string;'],
  //   args: 'customCommand',
  //   name: 'コマンド',
  //   description: 'コマンドを実行することができる。外部プログラムを呼び出し、画像処理などを行う。',
  // },
  {
    lowercamelcase: 'compose',
    uppercamelcase: 'Compose',
    snakecase: 'COMPOSE',
    argDefs: ['operator: ComposeOperator | string;'],
    args: 'operator',
    name: '合成',
    description:
      '複数の画像を合成することができる。合成モードや透明度などのパラメータを指定して、複数の画像を組み合わせることができる。',
  },
  {
    lowercamelcase: 'composite',
    uppercamelcase: 'Composite',
    snakecase: 'COMPOSITE',
    argDefs: ['changeImagePath: string;', 'maskImagePath?: string;'],
    args: 'changeImagePath,maskImagePath',
    name: '合成',
    description: '画像を合成することができる。複数の画像を組み合わせて1枚の画像を作成する。',
  },
  {
    lowercamelcase: 'compress',
    uppercamelcase: 'Compress',
    snakecase: 'COMPRESS',
    argDefs: ['compressionType: CompressionType | string;'],
    args: 'compressionType',
    name: '圧縮',
    description: '画像を圧縮することができる。圧縮率や圧縮形式を指定して、画像ファイルのサイズを減らすことができる。',
  },
  {
    lowercamelcase: 'contrast',
    uppercamelcase: 'Contrast',
    snakecase: 'CONTRAST',
    argDefs: ['multiplier: number;'],
    args: 'multiplier',
    name: 'コントラスト調整',
    description:
      '画像のコントラストを調整することができる。コントラストの調整により、画像の明るさと暗さの差を強調することができる。',
  },
  {
    lowercamelcase: 'convolve',
    uppercamelcase: 'Convolve',
    snakecase: 'CONVOLVE',
    argDefs: ['kernel: string;'],
    args: 'kernel',
    name: '畳み込みフィルタ',
    description:
      '画像に畳み込みフィルタを適用することができる。畳み込みフィルタを使用することで、画像の特徴を強調したり、ノイズを除去したりすることができる。',
  },
  // {
  //   lowercamelcase: 'createDirectories',
  //   uppercamelcase: 'CreateDirectories',
  //   snakecase: 'CREATE_DIRECTORIES',
  //   name: 'ディレクトリの作成',
  //   description:
  //     '指定されたパスにディレクトリを作成することができる。ディレクトリが存在しない場合は、自動的に作成される。',
  // },
  {
    lowercamelcase: 'crop',
    uppercamelcase: 'Crop',
    snakecase: 'CROP',
    argDefs: ['width: number;', 'height: number;', 'x?: number;', 'y?: number;', 'percent?: boolean;'],
    args: 'width,height,x,y,percent',
    name: '切り抜き',
    description: '画像を指定された範囲で切り取ることができる。指定された範囲外の部分が削除される。',
  },
  {
    lowercamelcase: 'cycle',
    uppercamelcase: 'Cycle',
    snakecase: 'CYCLE',
    argDefs: ['amount: number;'],
    args: 'amount',
    name: 'サイクル',
    description: '画像を指定された回数だけ複製して連結することができる。アニメーションのループなどに使用される。',
  },
  {
    lowercamelcase: 'deconstruct',
    uppercamelcase: 'Deconstruct',
    snakecase: 'DECONSTRUCT',
    name: '色成分の分解',
    description: '画像の色を成分ごとに分解することができる。RGBやCMYKなどの成分を個別に操作するのに使用される。',
  },
  {
    lowercamelcase: 'define',
    uppercamelcase: 'Define',
    snakecase: 'DEFINE',
    argDefs: ['value: string;'],
    args: 'value',
    name: 'パラメータ定義',
    description:
      '画像処理に関する設定やパラメータを定義することができる。処理の挙動や結果を細かく調整するのに使用される。',
  },
  {
    lowercamelcase: 'delay',
    uppercamelcase: 'Delay',
    snakecase: 'DELAY',
    argDefs: ['centiseconds: number;'],
    args: 'centiseconds',
    name: '遅延設定',
    description: 'アニメーション画像のフレーム間の遅延を設定することができる。各フレームの表示時間を制御する。',
  },
  {
    lowercamelcase: 'density',
    uppercamelcase: 'Density',
    snakecase: 'DENSITY',
    argDefs: ['width: number;', 'height: number;'],
    args: 'width,height',
    name: '解像度',
    description: '画像の解像度や密度を設定することができる。印刷や表示における画像の品質を調整するのに使用される。',
  },
  {
    lowercamelcase: 'despeckle',
    uppercamelcase: 'Despeckle',
    snakecase: 'DESPECKLE',
    name: 'スペックルノイズ除去',
    description: '画像からスペックルノイズを除去することができる。画像のクリーンアップや改善に使用される。',
  },
  {
    lowercamelcase: 'displace',
    uppercamelcase: 'Displace',
    snakecase: 'DISPLACE',
    argDefs: ['horizontal: number;', 'vertical: number;'],
    args: 'horizontal,vertical',
    name: 'ピクセル変位',
    description: '画像のピクセルを指定されたマップに基づいて変位させることができる。歪みや効果を与えるのに使用される。',
  },
  // {
  //   lowercamelcase: 'display',
  //   uppercamelcase: 'Display',
  //   snakecase: 'DISPLAY',
  //   argDefs: ['xServer: string;'],
  //   args: 'xServer',
  //   name: '表示',
  //   description: '画像を表示することができる。画像を表示するウィンドウやデバイスを指定して画像を表示する。',
  // },
  {
    lowercamelcase: 'dispose',
    uppercamelcase: 'Dispose',
    snakecase: 'DISPOSE',
    argDefs: ['method: DisposeMethod | string;'],
    args: 'method',
    name: '後処理',
    description:
      'アニメーション画像の各フレームの後処理方法を設定することができる。フレームの間のトランジションやクリア方法などを指定する。',
  },
  {
    lowercamelcase: 'dissolve',
    uppercamelcase: 'Dissolve',
    snakecase: 'DISSOLVE',
    argDefs: ['percent: number;'],
    args: 'percent',
    name: 'トランジション',
    description:
      '画像同士を指定された割合で混合することができる。トランジションやフェードイン/フェードアウトのエフェクトを作成するのに使用される。',
  },
  {
    lowercamelcase: 'dither',
    uppercamelcase: 'Dither',
    snakecase: 'DITHER',
    argDefs: ['enable?: boolean;'],
    args: 'enable',
    name: '減色',
    description: '画像の色を減色することができる。色数を減らすことで画像を効果的に圧縮するのに使用される。',
  },
  {
    lowercamelcase: 'edge',
    uppercamelcase: 'Edge',
    snakecase: 'EDGE',
    argDefs: ['radius?: number;'],
    args: 'radius',
    name: 'エッジ検出',
    description: '画像のエッジを検出することができる。エッジ検出により、画像の輪郭を強調することができる。',
  },
  {
    lowercamelcase: 'emboss',
    uppercamelcase: 'Emboss',
    snakecase: 'EMBOSS',
    argDefs: ['radius?: number;'],
    args: 'radius',
    name: 'エンボス効果',
    description: '画像に浮き出し効果を与えることができる。画像に立体感や質感を与えるのに使用される。',
  },
  {
    lowercamelcase: 'encoding',
    uppercamelcase: 'Encoding',
    snakecase: 'ENCODING',
    argDefs: ['encoding: Encoding | string;'],
    args: 'encoding',
    name: 'エンコーディング指定',
    description:
      '画像のエンコード方法や形式を指定することができる。画像のファイル形式や圧縮方法を設定するのに使用される。',
  },
  {
    lowercamelcase: 'endian',
    uppercamelcase: 'Endian',
    snakecase: 'ENDIAN',
    argDefs: ['endianType: EndianType | string;'],
    args: 'endianType',
    name: 'エンディアン',
    description:
      '画像のバイトオーダーを設定することができる。エンディアンの変更により、画像の解釈や表示が変わることがある。',
  },
  {
    lowercamelcase: 'enhance',
    uppercamelcase: 'Enhance',
    snakecase: 'ENHANCE',
    name: '鮮明度、色彩、コントラスト調整',
    description: '画像の品質を向上させることができる。画像の鮮明度、色彩、コントラストなどを調整するのに使用される。',
  },
  {
    lowercamelcase: 'equalize',
    uppercamelcase: 'Equalize',
    snakecase: 'EQUALIZE',
    name: 'ヒストグラム均等化',
    description:
      '画像のヒストグラムを均等化することができる。ヒストグラム均等化により、画像のコントラストを向上させることができる。',
  },
  {
    lowercamelcase: 'extent',
    uppercamelcase: 'Extent',
    snakecase: 'EXTENT',
    argDefs: ['width: number;', 'height: number;', 'options?: string;'],
    args: 'width,height,options',
    name: 'サイズ変更',
    description:
      '画像のサイズを変更することができる。指定されたサイズにリサイズするか、余白を追加してサイズを変更する。',
  },
  // {
  //   lowercamelcase: 'file',
  //   uppercamelcase: 'File',
  //   snakecase: 'FILE',
  //   argDefs: ['filename: string;'],
  //   args: 'filename',
  //   name: 'ファイル情報',
  //   description:
  //     '画像のファイル情報やメタデータを取得することができる。ファイルの種類やサイズ、作成日時などの情報を取得する。',
  // },
  {
    lowercamelcase: 'filter',
    uppercamelcase: 'Filter',
    snakecase: 'FILTER',
    argDefs: ['filterType: FilterType | string;'],
    args: 'filterType',
    name: 'フィルタ',
    description:
      '画像にフィルター処理を適用することができる。ぼかし、シャープ化、輪郭強調などのさまざまなエフェクトを実現することができる。',
  },
  {
    lowercamelcase: 'flatten',
    uppercamelcase: 'Flatten',
    snakecase: 'FLATTEN',
    name: 'レイヤー統合',
    description: '画像のレイヤーを平坦化することができる。複数の画像レイヤーを一つの画像に結合する。',
  },
  {
    lowercamelcase: 'flip',
    uppercamelcase: 'Flip',
    snakecase: 'FLIP',
    name: '上下反転',
    description: '画像を上下に反転させることができる。',
  },
  {
    lowercamelcase: 'flop',
    uppercamelcase: 'Flop',
    snakecase: 'FLOP',
    name: '左右反転',
    description: '画像を左右に反転させることができる。',
  },
  {
    lowercamelcase: 'foreground',
    uppercamelcase: 'Foreground',
    snakecase: 'FOREGROUND',
    argDefs: ['color: string;'],
    args: 'color',
    name: '前景色',
    description: '画像に前景色を指定することができる。文字や形状の描画などに使用される。',
  },
  {
    lowercamelcase: 'frame',
    uppercamelcase: 'Frame',
    snakecase: 'FRAME',
    argDefs: ['width: number;', 'height: number;', 'outerBevelWidth: number;', 'outBevelHeight: number;'],
    args: 'width,height,outerBevelWidth,outBevelHeight',
    name: '枠線追加',
    description: '画像に枠線を追加することができる。指定した色や太さで画像を枠で囲む。',
  },
  {
    lowercamelcase: 'fuzz',
    uppercamelcase: 'Fuzz',
    snakecase: 'FUZZ',
    argDefs: ['distance: number;', 'percent?: boolean;'],
    args: 'distance,percent',
    name: 'ぼかし',
    description: '画像の色の許容範囲を指定することができる。指定した色と近い色を同一視することができる。',
  },
  {
    lowercamelcase: 'gamma',
    uppercamelcase: 'Gamma',
    snakecase: 'GAMMA',
    argDefs: ['r: number;', 'g: number;', 'b: number;'],
    args: 'r,g,b',
    name: 'ガンマ補正',
    description: '画像のガンマ補正を行うことができる。画像の明るさやコントラストを調整するのに使用される。',
  },
  {
    lowercamelcase: 'gaussian',
    uppercamelcase: 'Gaussian',
    snakecase: 'GAUSSIAN',
    argDefs: ['radius: number;', 'sigma?: number;'],
    args: 'radius,sigma',
    name: 'ガウシアンぼかし',
    description:
      '画像にガウシアンぼかしを適用することができる。ガウシアンぼかしは、画像のエッジを滑らかにするのに使用される。',
  },
  {
    lowercamelcase: 'geometry',
    uppercamelcase: 'Geometry',
    snakecase: 'GEOMETRY',
    argDefs: ['width: number;', 'height?: number;', 'option?: ResizeOption;', 'geometry: string;'],
    args: 'width,height,option,geometry',
    name: '幅、高さ、位置調整',
    description: '画像の幅や高さ、位置を指定することができる。画像のサイズや配置を調整するのに使用される。',
  },
  {
    lowercamelcase: 'greenPrimary',
    uppercamelcase: 'GreenPrimary',
    snakecase: 'GREEN_PRIMARY',
    argDefs: ['x: number;', 'y: number;'],
    args: 'x,y',
    name: '緑の主要成分',
    description: '画像の緑のプライマリ値を設定することができる。',
  },
  {
    lowercamelcase: 'gravity',
    uppercamelcase: 'Gravity',
    snakecase: 'GRAVITY',
    argDefs: ['direction: GravityDirection | string;'],
    args: 'direction',
    name: '画像揃え基準点指定',
    description: '画像の揃える基準点を指定することができる。画像の配置や重心を制御するのに使用される。',
  },
  {
    lowercamelcase: 'highlightColor',
    uppercamelcase: 'HighlightColor',
    snakecase: 'HIGHLIGHT_COLOR',
    argDefs: ['color: string;'],
    args: 'color',
    name: 'ハイライトの色',
    description: '画像のハイライト色を指定することができる。ハイライトの色や強度を調整するのに使用される。',
  },
  {
    lowercamelcase: 'highlightStyle',
    uppercamelcase: 'HighlightStyle',
    snakecase: 'HIGHLIGHT_STYLE',
    argDefs: ['style: HighlightStyle | string;'],
    args: 'style',
    name: 'ハイライトのスタイル',
    description:
      '画像のハイライトのスタイルを指定することができる。ハイライトのスタイルや効果を変更するのに使用される。',
  },
  {
    lowercamelcase: 'iconGeometry',
    uppercamelcase: 'IconGeometry',
    snakecase: 'ICON_GEOMETRY',
    argDefs: ['geometry: string;'],
    args: 'geometry',
    name: 'アイコンのジオメトリ',
    description: 'アイコンのサイズや配置を指定することができる。',
  },
  {
    lowercamelcase: 'implode',
    uppercamelcase: 'Implode',
    snakecase: 'IMPLODE',
    argDefs: ['factor?: number;'],
    args: 'factor',
    name: '内側に収縮',
    description:
      '画像を内側に収縮させることができる。画像を中心点を基準に収縮することで、効果的な視覚的効果を得ることができる。',
  },
  // {
  //   lowercamelcase: 'in',
  //   uppercamelcase: 'In',
  //   snakecase: 'IN',
  //   argDefs: ['customArguments: string[];'],
  //   args: 'customArguments',
  //   name: '入力',
  //   description: '入力画像を設定することができる。処理の対象となる入力画像を指定する。',
  // },
  {
    lowercamelcase: 'intent',
    uppercamelcase: 'Intent',
    snakecase: 'INTENT',
    argDefs: ['intentType: IntentType | string;'],
    args: 'intentType',
    name: 'カラー管理操作',
    description: '画像の処理目的を指定することができる。色変換やリサイズなどの処理方法を指定する。',
  },
  {
    lowercamelcase: 'interlace',
    uppercamelcase: 'Interlace',
    snakecase: 'INTERLACE',
    argDefs: ['interlaceType: InterlaceType | string;'],
    args: 'interlaceType',
    name: 'インターレース',
    description:
      '画像のインターレース形式を設定することができる。プログレッシブ表示やインターレース表示などの方法を指定する。',
  },
  {
    lowercamelcase: 'label',
    uppercamelcase: 'Label',
    snakecase: 'LABEL',
    argDefs: ['name: string;'],
    args: 'name',
    name: 'ラベル',
    description: '画像にラベルを追加することができる。画像にテキストや注釈を付けるのに使用される。',
  },
  {
    lowercamelcase: 'lat',
    uppercamelcase: 'Lat',
    snakecase: 'LAT',
    argDefs: ['width: number;', 'height: number;', 'offset: number;', 'percent?: boolean;'],
    args: 'width,height,offset,percent',
    name: 'ローカル適応しきい値処理',
    description: '指定された幅、高さ、オフセットを使用して、ローカル適応しきい値処理を実行する。',
  },
  {
    lowercamelcase: 'level',
    uppercamelcase: 'Level',
    snakecase: 'LEVEL',
    argDefs: ['blackPoint: number;', 'gamma: number;', 'whitePoint: number;', 'percent?: boolean;'],
    args: 'blackPoint,gamma,whitePoint,percent',
    name: 'コントラストレベル調整',
    description: '画像のレベルを調整することができる。色の範囲を変更することで、コントラストや明るさを調整する。',
  },
  {
    lowercamelcase: 'limit',
    uppercamelcase: 'Limit',
    snakecase: 'LIMIT',
    argDefs: ['limitType: LimitType | string;', 'val: string;'],
    args: 'limitType,val',
    name: 'リソース制限',
    description: '画像処理に対するリソースの制限を設定することができる。メモリやCPUの使用量、処理速度などを制御する。',
  },
  {
    lowercamelcase: 'list',
    uppercamelcase: 'List',
    snakecase: 'LIST',
    argDefs: ['listType: ListType | string;'],
    args: 'listType',
    name: 'リスト',
    description:
      '画像ファイルや画像の属性をリストアップすることができる。画像のメタデータやファイル情報を取得するのに使用される。',
  },
  {
    lowercamelcase: 'log',
    uppercamelcase: 'Log',
    snakecase: 'LOG',
    argDefs: ['format: string;'],
    args: 'format',
    name: 'ログ',
    description: '画像処理のログを記録することができる。処理の進捗やエラーなどを記録するのに使用される。',
  },
  {
    lowercamelcase: 'loop',
    uppercamelcase: 'Loop',
    snakecase: 'LOOP',
    argDefs: ['iterations: number;'],
    args: 'iterations',
    name: 'ループ',
    description: '画像のアニメーションループを設定することができる。アニメーション画像の再生回数やループの制御を行う。',
  },
  {
    lowercamelcase: 'lower',
    uppercamelcase: 'Lower',
    snakecase: 'LOWER',
    argDefs: ['width: number;', 'height: number;'],
    args: 'width,height',
    name: '擬似的エッジ',
    description: '画像のエッジを擬似的に3Dに下げる効果を作成する。',
  },
  {
    lowercamelcase: 'magnify',
    uppercamelcase: 'Magnify',
    snakecase: 'MAGNIFY',
    argDefs: ['factor: number;'],
    args: 'factor',
    name: '拡大',
    description: '画像を拡大することができる。画像のサイズを拡大して、詳細な部分を表示するのに使用される。',
  },
  {
    lowercamelcase: 'map',
    uppercamelcase: 'Map',
    snakecase: 'MAP',
    argDefs: ['filename: string;'],
    args: 'filename',
    name: 'マップ',
    description: '画像のピクセル値をマッピングすることができる。指定されたカラーマップに基づいて、画像の色を変換する。',
  },
  {
    lowercamelcase: 'mask',
    uppercamelcase: 'Mask',
    snakecase: 'MASK',
    argDefs: ['filename: string;'],
    args: 'filename',
    name: 'マスク',
    description: '画像にマスクを適用することができる。指定されたマスクに基づいて、画像の一部を表示または非表示にする。',
  },
  {
    lowercamelcase: 'matte',
    uppercamelcase: 'Matte',
    snakecase: 'MATTE',
    name: 'マットチャネル保存',
    description:
      '画像にマットチャネルがある場合は、マットチャネルを保存する。画像の透過性や形状を調整することができる。',
  },
  {
    lowercamelcase: 'matteColor',
    uppercamelcase: 'MatteColor',
    snakecase: 'MATTE_COLOR',
    argDefs: ['color: string;'],
    args: 'color',
    name: 'マットチャネル色',
    description: '画像のマットの色を指定することができる。マットの色や透明度を調整するのに使用される。',
  },
  {
    lowercamelcase: 'maximumError',
    uppercamelcase: 'MaximumError',
    snakecase: 'MAXIMUM_ERROR',
    argDefs: ['limit: number;'],
    args: 'limit',
    name: 'エラー最大量',
    description: '合計画像エラーの最大量を指定する。',
  },
  {
    lowercamelcase: 'median',
    uppercamelcase: 'Median',
    snakecase: 'MEDIAN',
    argDefs: ['radius?: number;'],
    args: 'radius',
    name: 'メディアンフィルター',
    description:
      '画像のメディアンフィルターを適用することができる。メディアンフィルターは、画像のノイズを除去するのに使用される。',
  },
  {
    lowercamelcase: 'minify',
    uppercamelcase: 'Minify',
    snakecase: 'MINIFY',
    argDefs: ['factor: number;'],
    args: 'factor',
    name: '縮小',
    description: '画像を縮小することができる。画像のサイズを縮小して、ファイルサイズを減らすことができる。',
  },
  {
    lowercamelcase: 'mode',
    uppercamelcase: 'Mode',
    snakecase: 'MODE',
    argDefs: ['mode: OperationMode | string;'],
    args: 'mode',
    name: '動作モード',
    description: '画像のモードを設定することができる。カラーモードや画像の表示形式を指定するのに使用される。',
  },
  {
    lowercamelcase: 'modulate',
    uppercamelcase: 'Modulate',
    snakecase: 'MODULATE',
    argDefs: ['b: number;', 's?: number;', 'h?: number;'],
    args: 'b,s,h',
    name: '明るさ、彩度、色相変更',
    description: '画像の色相、彩度、明度を調整することができる。色のバランスや鮮やかさを調整するのに使用される。',
  },
  {
    lowercamelcase: 'monitor',
    uppercamelcase: 'Monitor',
    snakecase: 'MONITOR',
    name: 'モニター',
    description: '画像処理の進行状況を監視することができる。処理の進捗や統計情報などをリアルタイムで表示する。',
  },
  {
    lowercamelcase: 'monochrome',
    uppercamelcase: 'Monochrome',
    snakecase: 'MONOCHROME',
    name: 'モノクロ',
    description: '画像をモノクロームに変換することができる。白黒や二値化などのモノクローム処理が可能。',
  },
  {
    lowercamelcase: 'montage',
    uppercamelcase: 'Montage',
    snakecase: 'MONTAGE',
    argDefs: ['otherImg: string;'],
    args: 'otherImg',
    name: 'モンタージュ',
    description: '画像をモンタージュすることができる。複数の画像をタイル状に並べて1枚の画像にまとめる。',
  },
  {
    lowercamelcase: 'morph',
    uppercamelcase: 'Morph',
    snakecase: 'MORPH',
    argDefs: ['otherImg: string | string[];', 'outName: string;', 'callback?: WriteCallback;'],
    args: 'otherImg,outName,callback',
    name: 'モーフィング',
    description: '画像間のモーフィングを行うことができる。複数の画像間で形状や特徴を変化させるのに使用される。',
  },
  {
    lowercamelcase: 'mosaic',
    uppercamelcase: 'Mosaic',
    snakecase: 'MOSAIC',
    name: 'モザイク',
    description: '複数の画像をモザイク状に配置して一つの画像に結合することができる。画像のタイル表示などに使用される。',
  },
  {
    lowercamelcase: 'motionBlur',
    uppercamelcase: 'MotionBlur',
    snakecase: 'MOTION_BLUR',
    argDefs: ['radius: number;', 'sigma?: number;', 'angle?: number;'],
    args: 'radius,sigma,angle',
    name: 'モーションブラー',
    description: '画像にモーションブラー効果を追加することができる。画像の移動を模倣し、動きのある効果を与える。',
  },
  // {
  //   lowercamelcase: 'name',
  //   uppercamelcase: 'Name',
  //   snakecase: 'NAME',
  //   name: '名前',
  //   description: '画像の名前や識別子を設定することができる。画像に名前を付けて識別するのに使用される。',
  // },
  {
    lowercamelcase: 'negative',
    uppercamelcase: 'Negative',
    snakecase: 'NEGATIVE',
    name: '色の反転',
    description: 'すべてのピクセルをその補色で置き換える。色の反転を行い、画像の色を反転させる。',
  },
  {
    lowercamelcase: 'noise',
    uppercamelcase: 'Noise',
    snakecase: 'NOISE',
    argDefs: ['noiseType: NoiseType | string | number;'],
    args: 'noiseType',
    name: 'ノイズ',
    description: '画像にノイズを追加することができる。ランダムなノイズやパターンを画像に適用し、効果を与える。',
  },
  // {
  //   lowercamelcase: 'noop',
  //   uppercamelcase: 'Noop',
  //   snakecase: 'NOOP',
  //   name: '無効',
  //   description: '画像処理を行わずに、画像をそのまま返すことができる。何もしない処理を行う。',
  // },
  {
    lowercamelcase: 'normalize',
    uppercamelcase: 'Normalize',
    snakecase: 'NORMALIZE',
    name: '正規化',
    description: '画像の色や明るさを正規化することができる。色のバランスや明るさを一定の基準に合わせる。',
  },
  {
    lowercamelcase: 'opaque',
    uppercamelcase: 'Opaque',
    snakecase: 'OPAQUE',
    argDefs: ['color: string;'],
    args: 'color',
    name: '不透明',
    description: '画像の透明部分を不透明にすることができる。透明な部分を指定された色やパターンで塗りつぶす。',
  },
  {
    lowercamelcase: 'operator',
    uppercamelcase: 'Operator',
    snakecase: 'OPERATOR',
    argDefs: ['channel: string;', 'operator: ChannelOperator | string;', 'rvalue: number;', 'percent?: boolean;'],
    args: 'channel,operator,rvalue,percent',
    name: '演算子',
    description: '画像チャネルに数学演算子、ビット演算子、または値演算子を適用する。',
  },
  {
    lowercamelcase: 'orderedDither',
    uppercamelcase: 'OrderedDither',
    snakecase: 'ORDERED_DITHER',
    argDefs: ['channelType: ChannelType | string;', 'NxN: string;'],
    args: 'channelType,NxN',
    name: '順序付きディザリング',
    description:
      '画像にオーダーディザリングを適用することができる。ディザリング効果を画像に適用し、色の表現を改善する。',
  },
  // {
  //   lowercamelcase: 'out',
  //   uppercamelcase: 'Out',
  //   snakecase: 'OUT',
  //   argDefs: ['customArguments: string[];'],
  //   args: 'customArguments',
  //   name: '出力',
  //   description: '出力先を設定することができる。処理結果の出力先を指定する。',
  // },
  // {
  //   lowercamelcase: 'outputDirectory',
  //   uppercamelcase: 'OutputDirectory',
  //   snakecase: 'OUTPUT_DIRECTORY',
  //   argDefs: ['directory: string;'],
  //   args: 'directory',
  //   name: '出力ディレクトリ',
  //   description: '処理した画像を出力するディレクトリを指定することができる。画像の出力先を指定する。',
  // },
  {
    lowercamelcase: 'page',
    uppercamelcase: 'Page',
    snakecase: 'PAGE',
    argDefs: ['width: number;', 'height: number;', "arg?: '%' | '!' | '<' | '>' | string;"],
    args: 'width,height,arg',
    name: 'キャンバスのサイズ、位置',
    description: '画像のページサイズや配置を設定することができる。印刷やレイアウトの際に使用される。',
  },
  {
    lowercamelcase: 'pause',
    uppercamelcase: 'Pause',
    snakecase: 'PAUSE',
    argDefs: ['seconds: number;'],
    args: 'seconds',
    name: '一時停止',
    description: 'アニメーション ループ間で一時停止する。',
  },
  // {
  //   lowercamelcase: 'pen',
  //   uppercamelcase: 'Pen',
  //   snakecase: 'PEN',
  //   argDefs: ['color: string;'],
  //   args: 'color',
  //   name: 'ペン',
  //   description: '画像に線やパスを描画することができる。ペンのスタイルや太さを指定して、画像に線を描く。',
  // },
  {
    lowercamelcase: 'ping',
    uppercamelcase: 'Ping',
    snakecase: 'PING',
    name: '画像特性',
    description: '画像の特徴を効率的に判断する。',
  },
  {
    lowercamelcase: 'pointSize',
    uppercamelcase: 'PointSize',
    snakecase: 'POINT_SIZE',
    argDefs: ['size: number;'],
    args: 'size',
    name: 'ポイントサイズ',
    description: 'PostScript、X11、またはTrueTypeフォントのポイントサイズ。',
  },
  {
    lowercamelcase: 'noProfile',
    uppercamelcase: 'NoProfile',
    snakecase: 'NO_PROFILE',
    name: 'プロファイル削除',
    description: '画像からプロファイル情報を削除することができる。画像のメタデータからプロファイル情報を除去する。',
  },
  {
    lowercamelcase: 'preview',
    uppercamelcase: 'Preview',
    snakecase: 'PREVIEW',
    argDefs: ['previewType: PreviewType | string;'],
    args: 'previewType',
    name: 'プレビュー',
    description: '画像のプレビューを生成することができる。サムネイルやプレビュー画像を生成する。',
  },
  {
    lowercamelcase: 'paint',
    uppercamelcase: 'Paint',
    snakecase: 'PAINT',
    argDefs: ['radius: number;'],
    args: 'radius',
    name: '油絵効果',
    description: '油絵をシミュレートする。',
  },
  {
    lowercamelcase: 'process',
    uppercamelcase: 'Process',
    snakecase: 'PROCESS',
    argDefs: ['command: string;'],
    args: 'command',
    name: 'プロセス',
    description: 'プロセスモジュールを使用して一連の画像を処理する。',
  },
  {
    lowercamelcase: 'profile',
    uppercamelcase: 'Profile',
    snakecase: 'PROFILE',
    argDefs: ['filename: string;'],
    args: 'filename',
    name: 'プロファイル追加',
    description:
      '画像にプロファイル情報を適用することができる。画像の色空間や色の表現を定義するプロファイル情報を適用する。',
  },
  {
    lowercamelcase: 'progress',
    uppercamelcase: 'Progress',
    snakecase: 'PROGRESS',
    name: '進行状況',
    description: '画像処理の進行状況を表示することができる。処理の進捗状況や残り時間をリアルタイムで表示する。',
  },
  {
    lowercamelcase: 'randomThreshold',
    uppercamelcase: 'RandomThreshold',
    snakecase: 'RANDOM_THRESHOLD',
    argDefs: ['channelType: ChannelType;', 'LOWxHIGH: string;'],
    args: 'channelType,LOWxHIGH',
    name: 'ランダムしきい値',
    description: '画像のランダムしきい値処理を行うことができる。ランダムなしきい値を使用して、画像を二値化する。',
  },
  {
    lowercamelcase: 'quality',
    uppercamelcase: 'Quality',
    snakecase: 'QUALITY',
    argDefs: ['level: number;'],
    args: 'level',
    name: '画像品質',
    description:
      'JPEG/MIFF/PNG/TIFFの圧縮レベル。圧縮率や品質レベルを調整することで、画像のファイルサイズと品質のバランスを調整する。',
  },
  {
    lowercamelcase: 'raise',
    uppercamelcase: 'Raise',
    snakecase: 'RAISE',
    argDefs: ['width: number;', 'height: number;'],
    args: 'width,height',
    name: '浮き出し',
    description: '画像の端を明るくしたり暗くしたりする。指定した方向や程度で、画像の輪郭を浮き出し状にする。',
  },
  {
    lowercamelcase: 'recolor',
    uppercamelcase: 'Recolor',
    snakecase: 'RECOLOR',
    argDefs: ['matrix: string;'],
    args: 'matrix',
    name: '再着色',
    description: '色変換マトリックスを画像チャンネルに適用する。指定した色やパターンで、画像の色を変更する。',
  },
  {
    lowercamelcase: 'redPrimary',
    uppercamelcase: 'RedPrimary',
    snakecase: 'RED_PRIMARY',
    argDefs: ['x: number;', 'y: number;'],
    args: 'x,y',
    name: '赤の主要成分',
    description: '画像の赤のプライマリ値を設定することができる。',
  },
  {
    lowercamelcase: 'region',
    uppercamelcase: 'Region',
    snakecase: 'REGION',
    argDefs: ['width: number;', 'height: number;', 'x?: number;', 'y?: number;'],
    args: 'width,height,x,y',
    name: '領域指定',
    description: '画像の一部にオプションを適用する。指定した範囲内の画像処理を行う。',
  },
  // {
  //   lowercamelcase: 'remote',
  //   uppercamelcase: 'Remote',
  //   snakecase: 'REMOTE',
  //   name: 'リモート',
  //   description:
  //     '画像のリモート処理を実行することができる。リモートサーバーに画像を送信して処理を実行し、結果を取得する。',
  // },
  {
    lowercamelcase: 'render',
    uppercamelcase: 'Render',
    snakecase: 'RENDER',
    name: 'レンダリング',
    description: 'レンダリングベクター操作。',
  },
  {
    lowercamelcase: 'repage',
    uppercamelcase: 'Repage',
    snakecase: 'REPAGE',
    argDefs: [
      'width: number;',
      'height: number;',
      'xoff: number;',
      'yoff: number;',
      'arg?: string;',
      "reset: '+' | string;",
    ],
    args: 'width,height,xoff,yoff,arg,reset',
    name: 'ページ再設定',
    description: '画像のページ設定を調整することができる。画像のページ位置やサイズを調整する。',
  },
  {
    lowercamelcase: 'sample',
    uppercamelcase: 'Sample',
    snakecase: 'SAMPLE',
    argDefs: ['geometry: string;'],
    args: 'geometry',
    name: '拡大縮小',
    description: 'ピクセルサンプリングを使用して画像を拡大縮小する。',
  },
  {
    lowercamelcase: 'samplingFactor',
    uppercamelcase: 'SamplingFactor',
    snakecase: 'SAMPLING_FACTOR',
    argDefs: ['horizontalFactor: number;', 'verticalFactor: number;'],
    args: 'horizontalFactor,verticalFactor',
    name: 'クロマサブサンプリング係数',
    description: 'DPX、JPEG、MPEG、またはYUVエンコーダがクロマダウンサンプリングに使用するサンプリング係数を指定する。',
  },
  {
    lowercamelcase: 'rawSize',
    uppercamelcase: 'RawSize',
    snakecase: 'RAW_SIZE',
    argDefs: ['width: number;', 'height: number;', 'offset?: number;'],
    args: 'width,height,offset',
    name: '生のサイズ',
    description: '画像の生のサイズを指定することができる。',
  },
  {
    lowercamelcase: 'resample',
    uppercamelcase: 'Resample',
    snakecase: 'RESAMPLE',
    argDefs: ['horizontal: number;', 'vertical: number;'],
    args: 'horizontal,vertical',
    name: '再サンプリング',
    description: '画像を指定された水平および垂直解像度にリサンプルする。',
  },
  {
    lowercamelcase: 'resize',
    uppercamelcase: 'Resize',
    snakecase: 'RESIZE',
    argDefs: ['width: number;', 'height?: number;', 'option?: ResizeOption;'],
    args: 'width,height,option',
    name: 'リサイズ',
    description: '画像のリサイズを行うことができる。画像のサイズを指定した幅や高さに変更する。',
  },
  {
    lowercamelcase: 'roll',
    uppercamelcase: 'Roll',
    snakecase: 'ROLL',
    argDefs: ['horizontal: number;', 'vertical: number;'],
    args: 'horizontal,vertical',
    name: '垂直／水平回転',
    description: '画像を垂直または水平に回転させる。',
  },
  {
    lowercamelcase: 'rotate',
    uppercamelcase: 'Rotate',
    snakecase: 'ROTATE',
    argDefs: ['backgroundColor: string;', 'degrees: number;'],
    args: 'backgroundColor,degrees',
    name: '回転',
    description: '画像を回転させることができる。指定した角度だけ画像を回転させる。',
  },
  {
    lowercamelcase: 'scene',
    uppercamelcase: 'Scene',
    snakecase: 'SCENE',
    argDefs: ['index: number;'],
    args: 'index',
    name: 'シーン番号設定',
    description: '画像のシーン番号を設定することができる。複数のシーンが含まれる画像ファイルの特定のシーンを指定する。',
  },
  {
    lowercamelcase: 'scenes',
    uppercamelcase: 'Scenes',
    snakecase: 'SCENES',
    argDefs: ['start: number;', 'end: number;'],
    args: 'start,end',
    name: 'シーン番号の範囲設定',
    description: '画像内のシーンの範囲を指定することができる。',
  },
  {
    lowercamelcase: 'scale',
    uppercamelcase: 'Scale',
    snakecase: 'SCALE',
    argDefs: ['width: number;', 'height: number;'],
    args: 'width,height',
    name: 'スケール',
    description: '画像のスケーリングを行うことができる。画像のサイズを指定した倍率で拡大縮小する。',
  },
  // {
  //   lowercamelcase: 'screen',
  //   uppercamelcase: 'Screen',
  //   snakecase: 'SCREEN',
  //   name: 'スクリーン',
  //   description: '画像のスクリーン合成を行うことができる。画像を別の画像や背景と合成して表示する。',
  // },
  {
    lowercamelcase: 'segment',
    uppercamelcase: 'Segment',
    snakecase: 'SEGMENT',
    argDefs: ['clustherThreshold: number;', 'smoothingThreshold: number;'],
    args: 'clustherThreshold,smoothingThreshold',
    name: '画像分割',
    description: '画像をセグメント化して分割することができる。画像を領域ごとに分割し、個々の領域を処理する。',
  },
  {
    lowercamelcase: 'selectFrame',
    uppercamelcase: 'SelectFrame',
    snakecase: 'SELECT_FRAME',
    argDefs: ['frame: number;'],
    args: 'frame',
    name: 'フレーム選択',
    description: 'フレームを選択することができる。動画やGIF画像から特定のフレームを選択する。',
  },
  {
    lowercamelcase: 'sepia',
    uppercamelcase: 'Sepia',
    snakecase: 'SEPIA',
    name: 'セピア',
    description: '画像にセピア調の効果を追加することができる。古めかしい雰囲気を持つセピア色に変換する。',
  },
  {
    lowercamelcase: 'set',
    uppercamelcase: 'Set',
    snakecase: 'SET',
    argDefs: ['attribute: string;', 'value: string;'],
    args: 'attribute,value',
    name: '画像属性設定',
    description: '画像の特定の属性を設定することができる。画像のメタデータやプロパティを設定する。',
  },
  {
    lowercamelcase: 'setFormat',
    uppercamelcase: 'SetFormat',
    snakecase: 'SET_FORMAT',
    argDefs: ['format: string;'],
    args: 'format',
    name: 'フォーマット設定',
    description: '画像のフォーマットを設定することができる。画像のファイル形式や拡張子を指定する。',
  },
  {
    lowercamelcase: 'shade',
    uppercamelcase: 'Shade',
    snakecase: 'SHADE',
    argDefs: ['azimuth: number;', 'elevation: number;'],
    args: 'azimuth,elevation',
    name: '影',
    description: '遠方の光源を使用して画像に影を付ける。指定した方向や強度で影を付けることができる。',
  },
  {
    lowercamelcase: 'shadow',
    uppercamelcase: 'Shadow',
    snakecase: 'SHADOW',
    argDefs: ['radius: number;', 'sigma?: number;'],
    args: 'radius,sigma',
    name: 'シャドウ',
    description: 'モンタージュに影を付ける。',
  },
  {
    lowercamelcase: 'sharedMemory',
    uppercamelcase: 'SharedMemory',
    snakecase: 'SHARED_MEMORY',
    name: '共有メモリ',
    description: '画像を共有メモリにロードすることができる。他のプロセスと画像を共有するためのメモリ領域を確保する。',
  },
  {
    lowercamelcase: 'shave',
    uppercamelcase: 'Shave',
    snakecase: 'SHAVE',
    argDefs: ['width: number;', 'height: number;', 'percent?: boolean;'],
    args: 'width,height,percent',
    name: 'ピクセル削除',
    description: '画像の端からピクセルを削り取る。指定した幅や高さだけ画像の周囲を削除する。',
  },
  {
    lowercamelcase: 'sharpen',
    uppercamelcase: 'Sharpen',
    snakecase: 'SHARPEN',
    argDefs: ['radius: number;', 'sigma?: number;'],
    args: 'radius,sigma',
    name: 'シャープ化',
    description: '画像をシャープにすることができる。画像の輪郭や細部を強調することで、鮮明さを向上させる。',
  },
  {
    lowercamelcase: 'shear',
    uppercamelcase: 'Shear',
    snakecase: 'SHEAR',
    argDefs: ['xDegrees: number;', 'yDegress: number;'],
    args: 'xDegrees,yDegress',
    name: 'せん断',
    description: 'X軸またはY軸に沿って画像をせん断する。',
  },
  {
    lowercamelcase: 'silent',
    uppercamelcase: 'Silent',
    snakecase: 'SILENT',
    name: 'コンソール出力抑止',
    description: '画像処理の出力を抑制することができる。処理結果を出力せずに処理を行う。',
  },
  {
    lowercamelcase: 'snaps',
    uppercamelcase: 'Snaps',
    snakecase: 'SNAPS',
    argDefs: ['count: number;'],
    args: 'count',
    name: 'スナップショット',
    description: 'Xサーバー画面から複数の画像を取得し、アニメーションシーケンスを作成する。',
  },
  {
    lowercamelcase: 'solarize',
    uppercamelcase: 'Solarize',
    snakecase: 'SOLARIZE',
    argDefs: ['threshold: number;'],
    args: 'threshold',
    name: 'ソラライズ',
    description: 'しきい値レベルを超えるすべてのピクセルを無効にする。',
  },
  {
    lowercamelcase: 'spread',
    uppercamelcase: 'Spread',
    snakecase: 'SPREAD',
    argDefs: ['amount: number;'],
    args: 'amount',
    name: '拡散',
    description: '画像の色やパターンを拡散させることができる。色やパターンの広がりを調整する。',
  },
  {
    lowercamelcase: 'stegano',
    uppercamelcase: 'Stegano',
    snakecase: 'STEGANO',
    argDefs: ['offset: number;'],
    args: 'offset',
    name: '透かし非表示',
    description: '画像内の透かしを非表示にする。',
  },
  {
    lowercamelcase: 'stereo',
    uppercamelcase: 'Stereo',
    snakecase: 'STEREO',
    name: 'ステレオ',
    description: '画像をステレオ視用に処理することができる。左右の画像を立体視効果として合成する。',
  },
  {
    lowercamelcase: 'strip',
    uppercamelcase: 'Strip',
    snakecase: 'STRIP',
    name: 'プロファイル削除',
    description: '画像からすべてのプロファイルとテキスト属性を削除する。',
  },
  {
    lowercamelcase: 'swirl',
    uppercamelcase: 'Swirl',
    snakecase: 'SWIRL',
    argDefs: ['degrees: number;'],
    args: 'degrees',
    name: '渦巻き',
    description: '画像を渦巻状に歪ませることができる。指定した中心点を中心に画像を渦巻き状に回転させる。',
  },
  {
    lowercamelcase: 'textFont',
    uppercamelcase: 'TextFont',
    snakecase: 'TEXT_FONT',
    argDefs: ['font: string;'],
    args: 'font',
    name: 'テキストフォント指定',
    description: '画像にテキストを追加する際のフォントを指定することができる。',
  },
  {
    lowercamelcase: 'texture',
    uppercamelcase: 'Texture',
    snakecase: 'TEXTURE',
    argDefs: ['filename: string;'],
    args: 'filename',
    name: 'テクスチャ',
    description: '画像にテクスチャを適用することができる。別の画像やパターンを用いて、画像にテクスチャを施す。',
  },
  {
    lowercamelcase: 'threshold',
    uppercamelcase: 'Threshold',
    snakecase: 'THRESHOLD',
    argDefs: ['value: number;', 'percent?: boolean;'],
    args: 'value,percent',
    name: 'しきい値',
    description: '画像のしきい値処理を行うことができる。指定した閾値を超えるピクセルを二値化し、画像を分類する。',
  },
  {
    lowercamelcase: 'thumb',
    uppercamelcase: 'Thumb',
    snakecase: 'THUMB',
    argDefs: [
      'width: number;',
      'height: number;',
      'outName: string;',
      'quality?: number;',
      "align?: 'topleft' | 'center' | string;",
      'callback: WriteCallback;',
    ],
    args: 'width,height,outName,quality,align,callback',
    name: 'サムネイル',
    description: '画像のサイズを素早く変更する。画質よりも速度を重視。',
  },
  {
    lowercamelcase: 'thumbnail',
    uppercamelcase: 'Thumbnail',
    snakecase: 'THUMBNAIL',
    argDefs: ['width: number;', 'height: number;', 'options?: ResizeOption;'],
    args: 'width,height,options',
    name: 'サムネイル',
    description: '画像のサイズを素早く変更する。画質よりも速度を重視。',
  },
  {
    lowercamelcase: 'tile',
    uppercamelcase: 'Tile',
    snakecase: 'TILE',
    argDefs: ['filename: string;'],
    args: 'filename',
    name: 'タイル',
    description: '画像をタイル状に並べることができる。指定したパターンや配置で画像をタイル表示する。',
  },
  {
    lowercamelcase: 'title',
    uppercamelcase: 'Title',
    snakecase: 'TITLE',
    argDefs: ['title: string;'],
    args: 'title',
    name: 'タイトル',
    description: 'タイトルを設定することができる。画像や動画にタイトルを追加する。',
  },
  {
    lowercamelcase: 'transform',
    uppercamelcase: 'Transform',
    snakecase: 'TRANSFORM',
    argDefs: ['color: string;'],
    args: 'color',
    name: '変換',
    description: 'イメージを変換する。',
  },
  {
    lowercamelcase: 'transparent',
    uppercamelcase: 'Transparent',
    snakecase: 'TRANSPARENT',
    argDefs: ['color: string;'],
    args: 'color',
    name: '透明化',
    description: '指定した色を透明化し、画像の一部を透明にする。',
  },
  {
    lowercamelcase: 'treeDepth',
    uppercamelcase: 'TreeDepth',
    snakecase: 'TREE_DEPTH',
    argDefs: ['depth: number;'],
    args: 'depth',
    name: '減色アルゴリズムのツリーの深さ',
    description: '減色アルゴリズムのツリーの深さを指定することができる。',
  },
  {
    lowercamelcase: 'trim',
    uppercamelcase: 'Trim',
    snakecase: 'TRIM',
    name: 'トリミング',
    description: '画像から余白を自動的にトリミングすることができる。画像の周囲の余白を削除して、本来の内容を切り出す。',
  },
  {
    lowercamelcase: 'type',
    uppercamelcase: 'Type',
    snakecase: 'TYPE',
    argDefs: ['imageType: ImageType | string;'],
    args: 'imageType',
    name: 'タイプ',
    description: '2値、グレースケール、パレット、トゥルーカラー、トゥルーカラー+アルファなどを指定。',
  },
  // {
  //   lowercamelcase: 'update',
  //   uppercamelcase: 'Update',
  //   snakecase: 'UPDATE',
  //   argDefs: ['seconds: number;'],
  //   args: 'seconds',
  //   name: '更新',
  //   description: '画像ファイルが変更されたことを検出して再表示する。',
  // },
  {
    lowercamelcase: 'units',
    uppercamelcase: 'Units',
    snakecase: 'UNITS',
    argDefs: ['unitType: UnitType | string;'],
    args: 'unitType',
    name: '解像度の単位指定',
    description: '画像の単位を指定することができる。画像の単位をピクセル/インチ、ピクセル/センチなどで指定する。',
  },
  {
    lowercamelcase: 'unsharp',
    uppercamelcase: 'Unsharp',
    snakecase: 'UNSHARP',
    argDefs: ['radius: number;', 'sigma?: number;', 'amount?: number;', 'threshold?: number;'],
    args: 'radius,sigma,amount,threshold',
    name: 'アンシャープ',
    description: '画像にアンシャープマスクを適用することができる。画像の鮮明度を向上させるためのフィルタリングを行う。',
  },
  {
    lowercamelcase: 'usePixmap',
    uppercamelcase: 'UsePixmap',
    snakecase: 'USE_PIXMAP',
    name: 'ピクスマップの使用',
    description: '画像の表示にピクスマップを使用するかどうかを設定することができる。',
  },
  {
    lowercamelcase: 'view',
    uppercamelcase: 'View',
    snakecase: 'VIEW',
    name: '表示パラメータ指定',
    description: 'FlashPix表示パラメータ指定。',
  },
  {
    lowercamelcase: 'virtualPixel',
    uppercamelcase: 'VirtualPixel',
    snakecase: 'VIRTUAL_PIXEL',
    argDefs: ['method: VirtualPixelMethod | string;'],
    args: 'method',
    name: '仮想ピクセル',
    description: '仮想ピクセルの設定を行うことができる。画像の範囲外のピクセルをどのように扱うかを指定する。',
  },
  {
    lowercamelcase: 'visual',
    uppercamelcase: 'Visual',
    snakecase: 'VISUAL',
    argDefs: ['visualType: VisualType | string;'],
    args: 'visualType',
    name: 'ビジュアル',
    description: 'このXビジュアル タイプを使用して画像をアニメーション化する。',
  },
  {
    lowercamelcase: 'watermark',
    uppercamelcase: 'Watermark',
    snakecase: 'WATERMARK',
    argDefs: ['brightness: number;', 'saturation: number;'],
    args: 'brightness,saturation',
    name: 'ウォーターマーク',
    description: '透かしの明るさと彩度のパーセント指定。',
  },
  {
    lowercamelcase: 'wave',
    uppercamelcase: 'Wave',
    snakecase: 'WAVE',
    argDefs: ['amplitude: number;', 'wavelength: number;'],
    args: 'amplitude,wavelength',
    name: '正弦波',
    description: '正弦波に沿って画像を変更する。',
  },
  {
    lowercamelcase: 'whitePoint',
    uppercamelcase: 'WhitePoint',
    snakecase: 'WHITE_POINT',
    argDefs: ['x: number;', 'y: number;'],
    args: 'x,y',
    name: 'ホワイトポイント',
    description: '画像のホワイトポイントを設定することができる。画像のホワイトポイントを調整する。',
  },
  {
    lowercamelcase: 'whiteThreshold',
    uppercamelcase: 'WhiteThreshold',
    snakecase: 'WHITE_THRESHOLD',
    argDefs: ['red: number;', 'green: number;', 'blue: number;', 'opacity?: number;', 'intensity: number;'],
    args: 'red,green,blue,opacity,intensity',
    name: 'ホワイトのしきい値',
    description: '画像のホワイトのしきい値を設定することができる。白色のピクセルとして扱うしきい値を設定する。',
  },
  // {
  //   lowercamelcase: 'window',
  //   uppercamelcase: 'Window',
  //   snakecase: 'WINDOW',
  //   argDefs: ['id: string;'],
  //   args: 'id',
  //   name: 'ウィンドウ',
  //   description: '画像のウィンドウ情報を取得することができる。画像のウィンドウ位置やサイズなどを取得する。',
  // },
  // {
  //   lowercamelcase: 'windowGroup',
  //   uppercamelcase: 'WindowGroup',
  //   snakecase: 'WINDOW_GROUP',
  //   name: 'ウィンドウグループ',
  //   description: '画像のウィンドウグループ情報を取得することができる。画像のウィンドウをグループ化する情報を取得する。',
  // },
];
